name: catolica
description: Exibe a programação da Semana de TI da Catolica

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: 1.1.1
  flutter_mobx: 1.1.0
  provider: 4.0.4
  rxdart: 0.23.1

  shared_preferences: 0.5.6+3

  bot_toast: ^2.3.1
  intl: 0.16.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.8.1
  mobx_codegen: 1.0.3

flutter:
  uses-material-design: true